SELECT * FROM <http://localhost:8081/fuseki/Dataset/data/patentMetadata> where{
    ?Dataset <http://www.ftn.uns.ac.rs/rdf/examples/predicate/priznatDatumPodnosenja> ?priznatDatumPodnosenja .
    FILTER(CONTAINS(UCASE(str(?priznatDatumPodnosenja)), UCASE("{{priznatDatumPodnosenja}}"))).
}