SELECT * FROM <http://localhost:8081/fuseki/Dataset/data/patentMetadata> where{
    ?Dataset <http://www.ftn.uns.ac.rs/rdf/examples/predicate/brojPrijave> ?brojPrijave .
    FILTER(CONTAINS(UCASE(str(?brojPrijave)), UCASE("{{brojPrijave}}"))).
}