//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.08 at 11:10:33 AM CET 
//


package Patent.BackendPatent.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.uns.ftn.p_1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.uns.ftn.p_1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link P1 }
     * 
     */
    public P1 createP1() {
        return new P1();
    }

    /**
     * Create an instance of {@link TipNazivPronalaska }
     * 
     */
    public TipNazivPronalaska createTipNazivPronalaska() {
        return new TipNazivPronalaska();
    }

    /**
     * Create an instance of {@link TipPopunjavaZavod }
     * 
     */
    public TipPopunjavaZavod createTipPopunjavaZavod() {
        return new TipPopunjavaZavod();
    }

    /**
     * Create an instance of {@link P1 .PopunjavaZavod }
     * 
     */
    public P1 .PopunjavaZavod createP1PopunjavaZavod() {
        return new P1 .PopunjavaZavod();
    }

    /**
     * Create an instance of {@link P1 .NazivPronalaska }
     * 
     */
    public P1 .NazivPronalaska createP1NazivPronalaska() {
        return new P1 .NazivPronalaska();
    }

    /**
     * Create an instance of {@link TipPodnosilacPrijave }
     * 
     */
    public TipPodnosilacPrijave createTipPodnosilacPrijave() {
        return new TipPodnosilacPrijave();
    }

    /**
     * Create an instance of {@link TipPronalazac }
     * 
     */
    public TipPronalazac createTipPronalazac() {
        return new TipPronalazac();
    }

    /**
     * Create an instance of {@link TipPunomocnik }
     * 
     */
    public TipPunomocnik createTipPunomocnik() {
        return new TipPunomocnik();
    }

    /**
     * Create an instance of {@link TipDostavljanje }
     * 
     */
    public TipDostavljanje createTipDostavljanje() {
        return new TipDostavljanje();
    }

    /**
     * Create an instance of {@link TipTipPrijave }
     * 
     */
    public TipTipPrijave createTipTipPrijave() {
        return new TipTipPrijave();
    }

    /**
     * Create an instance of {@link TipZahtevZaPriznanjePravaPrvenstvaIzRanijihPrijava }
     * 
     */
    public TipZahtevZaPriznanjePravaPrvenstvaIzRanijihPrijava createTipZahtevZaPriznanjePravaPrvenstvaIzRanijihPrijava() {
        return new TipZahtevZaPriznanjePravaPrvenstvaIzRanijihPrijava();
    }

    /**
     * Create an instance of {@link TipAdresaDostavljanje }
     * 
     */
    public TipAdresaDostavljanje createTipAdresaDostavljanje() {
        return new TipAdresaDostavljanje();
    }

    /**
     * Create an instance of {@link TipAdresa }
     * 
     */
    public TipAdresa createTipAdresa() {
        return new TipAdresa();
    }

    /**
     * Create an instance of {@link TipFirma }
     * 
     */
    public TipFirma createTipFirma() {
        return new TipFirma();
    }

    /**
     * Create an instance of {@link TipRanijaPrijava }
     * 
     */
    public TipRanijaPrijava createTipRanijaPrijava() {
        return new TipRanijaPrijava();
    }

    /**
     * Create an instance of {@link TipOsoba }
     * 
     */
    public TipOsoba createTipOsoba() {
        return new TipOsoba();
    }

    /**
     * Create an instance of {@link TipPrebivaliste }
     * 
     */
    public TipPrebivaliste createTipPrebivaliste() {
        return new TipPrebivaliste();
    }

    /**
     * Create an instance of {@link TipNacin }
     * 
     */
    public TipNacin createTipNacin() {
        return new TipNacin();
    }

    /**
     * Create an instance of {@link TipNaziv }
     * 
     */
    public TipNaziv createTipNaziv() {
        return new TipNaziv();
    }

    /**
     * Create an instance of {@link TipKontakt }
     * 
     */
    public TipKontakt createTipKontakt() {
        return new TipKontakt();
    }

    /**
     * Create an instance of {@link TipLicneInformacije }
     * 
     */
    public TipLicneInformacije createTipLicneInformacije() {
        return new TipLicneInformacije();
    }

    /**
     * Create an instance of {@link TipNazivPronalaska.SrpskiNaziv }
     * 
     */
    public TipNazivPronalaska.SrpskiNaziv createTipNazivPronalaskaSrpskiNaziv() {
        return new TipNazivPronalaska.SrpskiNaziv();
    }

    /**
     * Create an instance of {@link TipNazivPronalaska.EngleskiNaziv }
     * 
     */
    public TipNazivPronalaska.EngleskiNaziv createTipNazivPronalaskaEngleskiNaziv() {
        return new TipNazivPronalaska.EngleskiNaziv();
    }

    /**
     * Create an instance of {@link TipPopunjavaZavod.BrojPrijave }
     * 
     */
    public TipPopunjavaZavod.BrojPrijave createTipPopunjavaZavodBrojPrijave() {
        return new TipPopunjavaZavod.BrojPrijave();
    }

}
