//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.11 at 06:50:29 PM CET 
//


package Patent.BackendPatent.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tipTipPrijave complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tipTipPrijave">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="da_li_je_dopunska_prijava" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="da_li_je_izdvojena_prijava" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="broj_prvobitne_prijave" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="datum_podnosenja_prvobitne_prijave" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tipTipPrijave", propOrder = {
    "daLiJeDopunskaPrijava",
    "daLiJeIzdvojenaPrijava",
    "brojPrvobitnePrijave",
    "datumPodnosenjaPrvobitnePrijave"
})
public class TipTipPrijave {

    @XmlElement(name = "da_li_je_dopunska_prijava")
    protected boolean daLiJeDopunskaPrijava;
    @XmlElement(name = "da_li_je_izdvojena_prijava")
    protected boolean daLiJeIzdvojenaPrijava;
    @XmlElement(name = "broj_prvobitne_prijave")
    protected int brojPrvobitnePrijave;
    @XmlElement(name = "datum_podnosenja_prvobitne_prijave", required = true)
    protected String datumPodnosenjaPrvobitnePrijave;

    /**
     * Gets the value of the daLiJeDopunskaPrijava property.
     * 
     */
    public boolean isDaLiJeDopunskaPrijava() {
        return daLiJeDopunskaPrijava;
    }

    /**
     * Sets the value of the daLiJeDopunskaPrijava property.
     * 
     */
    public void setDaLiJeDopunskaPrijava(boolean value) {
        this.daLiJeDopunskaPrijava = value;
    }

    /**
     * Gets the value of the daLiJeIzdvojenaPrijava property.
     * 
     */
    public boolean isDaLiJeIzdvojenaPrijava() {
        return daLiJeIzdvojenaPrijava;
    }

    /**
     * Sets the value of the daLiJeIzdvojenaPrijava property.
     * 
     */
    public void setDaLiJeIzdvojenaPrijava(boolean value) {
        this.daLiJeIzdvojenaPrijava = value;
    }

    /**
     * Gets the value of the brojPrvobitnePrijave property.
     * 
     */
    public int getBrojPrvobitnePrijave() {
        return brojPrvobitnePrijave;
    }

    /**
     * Sets the value of the brojPrvobitnePrijave property.
     * 
     */
    public void setBrojPrvobitnePrijave(int value) {
        this.brojPrvobitnePrijave = value;
    }

    /**
     * Gets the value of the datumPodnosenjaPrvobitnePrijave property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatumPodnosenjaPrvobitnePrijave() {
        return datumPodnosenjaPrvobitnePrijave;
    }

    /**
     * Sets the value of the datumPodnosenjaPrvobitnePrijave property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatumPodnosenjaPrvobitnePrijave(String value) {
        this.datumPodnosenjaPrvobitnePrijave = value;
    }

}
