//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.29 at 10:39:47 AM CET 
//


package Patent.BackendPatent.model.resenjePatent;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="datum_odluke_o_zahtevu">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="about" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="datatype" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="da_li_je_prosao" type="{http://www.ftn.uns.rs/ResenjePatent}tipProlaz"/>
 *         &lt;element name="sluzbenik">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.ftn.uns.rs/ResenjePatent}tipSluzbenik">
 *                 &lt;attribute name="about" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="referenca_na_zahtev" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "datumOdlukeOZahtevu",
    "daLiJeProsao",
    "sluzbenik",
    "referencaNaZahtev"
})
@XmlRootElement(name = "resenje")
public class Resenje {

    @XmlElement(name = "datum_odluke_o_zahtevu", required = true)
    protected DatumOdlukeOZahtevu datumOdlukeOZahtevu;
    @XmlElement(name = "da_li_je_prosao", required = true)
    protected TipProlaz daLiJeProsao;
    @XmlElement(required = true)
    protected Sluzbenik sluzbenik;
    @XmlElement(name = "referenca_na_zahtev", required = true)
    protected String referencaNaZahtev;
    @XmlAttribute(name = "id")
    protected String id;

    /**
     * Gets the value of the datumOdlukeOZahtevu property.
     * 
     * @return
     *     possible object is
     *     {@link DatumOdlukeOZahtevu }
     *     
     */
    public DatumOdlukeOZahtevu getDatumOdlukeOZahtevu() {
        return datumOdlukeOZahtevu;
    }

    /**
     * Sets the value of the datumOdlukeOZahtevu property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatumOdlukeOZahtevu }
     *     
     */
    public void setDatumOdlukeOZahtevu(DatumOdlukeOZahtevu value) {
        this.datumOdlukeOZahtevu = value;
    }

    /**
     * Gets the value of the daLiJeProsao property.
     * 
     * @return
     *     possible object is
     *     {@link TipProlaz }
     *     
     */
    public TipProlaz getDaLiJeProsao() {
        return daLiJeProsao;
    }

    /**
     * Sets the value of the daLiJeProsao property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipProlaz }
     *     
     */
    public void setDaLiJeProsao(TipProlaz value) {
        this.daLiJeProsao = value;
    }

    /**
     * Gets the value of the sluzbenik property.
     * 
     * @return
     *     possible object is
     *     {@link Sluzbenik }
     *     
     */
    public Sluzbenik getSluzbenik() {
        return sluzbenik;
    }

    /**
     * Sets the value of the sluzbenik property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sluzbenik }
     *     
     */
    public void setSluzbenik(Sluzbenik value) {
        this.sluzbenik = value;
    }

    /**
     * Gets the value of the referencaNaZahtev property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferencaNaZahtev() {
        return referencaNaZahtev;
    }

    /**
     * Sets the value of the referencaNaZahtev property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferencaNaZahtev(String value) {
        this.referencaNaZahtev = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="about" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="datatype" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class DatumOdlukeOZahtevu {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "about")
        protected String about;
        @XmlAttribute(name = "property")
        protected String property;
        @XmlAttribute(name = "datatype")
        protected String datatype;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the about property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAbout() {
            return about;
        }

        /**
         * Sets the value of the about property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAbout(String value) {
            this.about = value;
        }

        /**
         * Gets the value of the property property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProperty() {
            return property;
        }

        /**
         * Sets the value of the property property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProperty(String value) {
            this.property = value;
        }

        /**
         * Gets the value of the datatype property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDatatype() {
            return datatype;
        }

        /**
         * Sets the value of the datatype property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDatatype(String value) {
            this.datatype = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.ftn.uns.rs/ResenjePatent}tipSluzbenik">
     *       &lt;attribute name="about" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Sluzbenik
        extends TipSluzbenik
    {

        @XmlAttribute(name = "about")
        protected String about;

        /**
         * Gets the value of the about property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAbout() {
            return about;
        }

        /**
         * Sets the value of the about property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAbout(String value) {
            this.about = value;
        }

    }

}
