//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.01 at 09:27:33 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ftn.uns.rs/KorisnikDTO", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package Patent.BackendPatent.dto.KorisnikDTO;
